import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { runSlicerEngine, verifyPrusaSlicer } from '../src/engine.js';

test('verifies PrusaSlicer through its supported help action', async t => {
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), 'slicer-engine-version-'));
  const executablePath = path.join(workDir, 'prusa-slicer-test-double');
  t.after(async () => {
    await fs.rm(workDir, { recursive: true, force: true });
  });

  await fs.writeFile(executablePath, `#!/bin/sh
if [ "$1" != "--help" ]; then
  printf '%s\\n' 'Unsupported version probe' >&2
  exit 2
fi
printf '%s\\n' 'PrusaSlicer-2.9.3+UNKNOWN based on Slic3r (without GUI support)'
`, { mode: 0o755 });

  const version = await verifyPrusaSlicer({
    prusaSlicerCommand: executablePath,
    workRoot: workDir,
    requestTimeoutMs: 30_000,
    maximumLogBytes: 64 * 1024
  });

  assert.equal(version, 'PrusaSlicer-2.9.3+UNKNOWN based on Slic3r (without GUI support)');
});

test('canonicalizes the generated timestamp before recording output evidence', async t => {
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), 'slicer-engine-output-'));
  const executablePath = path.join(workDir, 'prusa-slicer-test-double');
  const inputPath = path.join(workDir, 'input.3mf');
  t.after(async () => {
    await fs.rm(workDir, { recursive: true, force: true });
  });

  await fs.writeFile(inputPath, 'fixture');
  await fs.writeFile(executablePath, `#!/bin/sh
output=''
while [ "$#" -gt 0 ]; do
  if [ "$1" = "--output" ]; then
    shift
    output="$1"
  fi
  shift
done
printf '%s\\n' '; generated by PrusaSlicer 2.9.3 on 2026-09-03 at 18:12:34 UTC' '; LAYER_CHANGE' 'G28' > "$output"
`, { mode: 0o755 });

  const result = await runSlicerEngine({
    plateInputPaths: [inputPath],
    effectiveConfiguration: { prusaConfig: { layer_height: 0.2 } },
    workDir,
    config: {
      prusaSlicerCommand: executablePath,
      jobTimeoutMs: 30_000,
      maximumLogBytes: 64 * 1024,
      maximumGcodeBytes: 64 * 1024,
      engineThreads: 1
    }
  });

  assert.match(
    await fs.readFile(result.gcodePath, 'utf8'),
    /^; generated by PrusaSlicer 2\.9\.3 on 1970-01-01 at 00:00:00 UTC$/m
  );
  assert.match(result.artifact.checksumSha256, /^[0-9a-f]{64}$/);
  assert.equal(result.metrics.layerCount, 1);
});
