import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { canonicalizeGcodeHeader } from '../src/gcode.js';

const withTempGcode = async (t, payload) => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'slicer-gcode-'));
  const gcodePath = path.join(directory, 'output.gcode');
  t.after(async () => {
    await fs.rm(directory, { recursive: true, force: true });
  });
  await fs.writeFile(gcodePath, payload);
  return gcodePath;
};

test('canonicalizes only the PrusaSlicer generator timestamp', async t => {
  const gcodePath = await withTempGcode(t, [
    '; generated by PrusaSlicer 2.9.3+UNKNOWN based on Slic3r (without GUI support) on 2026-09-03 at 17:59:01 UTC',
    '; AM_PILOT_QUALIFICATION_START',
    'G90',
    ''
  ].join('\n'));

  await canonicalizeGcodeHeader(gcodePath);

  assert.equal(await fs.readFile(gcodePath, 'utf8'), [
    '; generated by PrusaSlicer 2.9.3+UNKNOWN based on Slic3r (without GUI support) on 1970-01-01 at 00:00:00 UTC',
    '; AM_PILOT_QUALIFICATION_START',
    'G90',
    ''
  ].join('\n'));
});

test('preserves CRLF and is idempotent', async t => {
  const payload = [
    '; generated by PrusaSlicer 2.9.3 on 1970-01-01 at 00:00:00 UTC',
    'G28',
    ''
  ].join('\r\n');
  const gcodePath = await withTempGcode(t, payload);

  await canonicalizeGcodeHeader(gcodePath);
  await canonicalizeGcodeHeader(gcodePath);

  assert.equal(await fs.readFile(gcodePath, 'utf8'), payload);
});

test('fails closed on an unexpected first-line header', async t => {
  const gcodePath = await withTempGcode(t, '; generated by a substituted engine\nG28\n');

  await assert.rejects(
    canonicalizeGcodeHeader(gcodePath),
    error => error?.code === 'slicer_gcode_header_invalid'
  );
});

test('fails closed on a different PrusaSlicer version header', async t => {
  const gcodePath = await withTempGcode(
    t,
    '; generated by PrusaSlicer 2.9.4 on 2026-09-03 at 17:59:01 UTC\nG28\n'
  );

  await assert.rejects(
    canonicalizeGcodeHeader(gcodePath),
    error => error?.code === 'slicer_gcode_header_invalid'
  );
});
