import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';

import { buildResultManifest, buildSliceEvidenceChecksum } from '../src/manifest.js';
import {
  compileProductionToolpath,
  PRODUCTION_TOOLPATH_MAGIC,
  PRODUCTION_TOOLPATH_PREFIX_BYTES,
  PRODUCTION_TOOLPATH_RECORD_BYTES
} from '../src/toolpath.js';

const sha256 = value => createHash('sha256').update(value).digest('hex');
const digest = value => `sha256:${value.repeat(64).slice(0, 64)}`;

const run = Object.freeze({
  id: 'run-toolpath-01',
  inputFingerprint: digest('a'),
  engineKey: 'fdm.am_pilot_prusa_core',
  engineVersionId: 'engine-02',
  engineImageDigest: digest('b'),
  capabilityRevisionId: 'fdm-prusa-2.9.3-protocol1-r2',
  effectiveConfigurationChecksumSha256: 'c'.repeat(64)
});

const effectiveConfiguration = Object.freeze({
  coordinateMapping: Object.freeze({
    projectOrigin: 'center',
    engineBedOrigin: 'front_left',
    translationMm: Object.freeze({ x: 100, y: 100, z: 0 })
  }),
  prusaConfig: Object.freeze({ filament_diameter: 1.75 })
});

const gcode = `; generated by PrusaSlicer 2.9.3 on 1970-01-01 at 00:00:00 UTC
G90
M83
G1 X100 Y100 Z0.2 F6000
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;TYPE:External perimeter
;WIDTH:0.45
G1 X110 Y100 E1 F1200
G1 X110 Y105 F600
G1 E-0.8 F1800
G1 E0.8 F1800
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
G1 Z0.4 F600
;TYPE:Internal infill
;WIDTH:0.46
G1 X100 Y100 E2 F1800
; estimated printing time (normal mode) = 1m 2s
; filament used [mm] = 3
`;

const artifactFor = async (workDir, source = gcode, summary = { layerCount: 2, estimatedTimeSeconds: 62 }) => {
  const gcodePath = path.join(workDir, 'output.gcode');
  await fs.writeFile(gcodePath, source, { mode: 0o600 });
  const gcodeArtifact = Object.freeze({
    checksumSha256: sha256(source),
    sizeBytes: Buffer.byteLength(source),
    contentType: 'text/x.gcode'
  });
  const result = Object.freeze({ artifact: gcodeArtifact, metrics: summary, warnings: [] });
  const sliceEvidenceChecksumSha256 = buildSliceEvidenceChecksum({ run, result });
  return await compileProductionToolpath({
    gcodePath,
    workDir,
    run,
    effectiveConfiguration,
    gcodeArtifact,
    sliceEvidenceChecksumSha256,
    summary,
    warnings: [],
    maximumBytes: 2 * 1024 * 1024
  });
};

const readContainer = buffer => {
  assert.equal(buffer.subarray(0, 8).toString('ascii'), PRODUCTION_TOOLPATH_MAGIC);
  assert.equal(buffer.readUInt32LE(8), 1);
  const headerLength = buffer.readUInt32LE(12);
  const header = JSON.parse(buffer.subarray(
    PRODUCTION_TOOLPATH_PREFIX_BYTES,
    PRODUCTION_TOOLPATH_PREFIX_BYTES + headerLength
  ).toString('utf8'));
  const payloadOffset = Math.ceil((PRODUCTION_TOOLPATH_PREFIX_BYTES + headerLength) / 8) * 8;
  return { header, records: new DataView(buffer.buffer, buffer.byteOffset + payloadOffset) };
};

test('compiles deterministic center-origin production toolpaths with layer and feature evidence', async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'slicer-toolpath-'));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const firstRoot = path.join(root, 'first');
  const secondRoot = path.join(root, 'second');
  await fs.mkdir(firstRoot);
  await fs.mkdir(secondRoot);

  const first = await artifactFor(firstRoot);
  const second = await artifactFor(secondRoot);
  assert.equal(
    first.header.source.sliceEvidenceChecksumSha256,
    '1866298d917a73f8f80f0ac86b2ef3d1ef42af9c1ccf091ffea06d585b65358a'
  );
  const firstBytes = await fs.readFile(first.path);
  const secondBytes = await fs.readFile(second.path);
  assert.deepEqual(firstBytes, secondBytes);
  assert.equal(first.artifact.checksumSha256, sha256(firstBytes));
  assert.equal(first.artifact.contentType, 'application/vnd.am-pilot.production-toolpath');

  const { header, records } = readContainer(firstBytes);
  assert.equal(header.source.runId, run.id);
  assert.equal(header.source.gcodeChecksumSha256, sha256(gcode));
  assert.equal(header.coordinateSystem.plateOrigin, 'center');
  assert.equal(header.recordCount, 6);
  assert.equal(header.layerCount, 2);
  assert.deepEqual(header.layers.map(layer => layer.recordCount), [4, 2]);
  assert.equal(header.catalogs.features[2].key, 'external_perimeter');
  assert.equal(header.statistics.moveRecordCounts.extrusion, 2);
  assert.equal(header.statistics.moveRecordCounts.travel, 2);
  assert.equal(header.statistics.moveRecordCounts.retraction, 1);
  assert.equal(header.statistics.moveRecordCounts.unretraction, 1);

  assert.equal(records.getFloat32(0, true), 0);
  assert.equal(records.getFloat32(4, true), 0);
  assert.equal(records.getFloat32(12, true), 10);
  assert.equal(records.getUint8(52), 1);
  assert.equal(records.getUint8(53), 2);
  const secondLayerOffset = 4 * PRODUCTION_TOOLPATH_RECORD_BYTES;
  assert.equal(records.getUint32(secondLayerOffset + 44, true), 1);
  assert.equal(records.getUint8(secondLayerOffset + 52), 0);

  const manifest = buildResultManifest({
    run,
    result: { artifact: { checksumSha256: sha256(gcode) }, metrics: { layerCount: 2 }, warnings: [] },
    toolpathPreview: first.artifact,
    sliceEvidenceChecksumSha256: header.source.sliceEvidenceChecksumSha256
  });
  assert.deepEqual(manifest.outputs.toolpathPreview, first.artifact);
  assert.equal(manifest.sliceEvidenceChecksumSha256, header.source.sliceEvidenceChecksumSha256);
});

test('fails closed when post-layer G-code requires an unsupported motion dialect', async t => {
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), 'slicer-toolpath-unsupported-'));
  t.after(() => fs.rm(workDir, { recursive: true, force: true }));
  await assert.rejects(
    artifactFor(workDir, `${gcode}\nG2 X1 Y1 I0.5 J0.5\n`),
    { code: 'slicer_toolpath_command_unsupported' }
  );
});

test('fails closed on unreviewed post-layer coordinate-state commands', async t => {
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), 'slicer-toolpath-state-'));
  t.after(() => fs.rm(workDir, { recursive: true, force: true }));
  await assert.rejects(
    artifactFor(workDir, `${gcode}\nG28 X\n`),
    { code: 'slicer_toolpath_command_unsupported' }
  );
});

test('fails closed when the toolpath artifact exceeds its explicit byte limit', async t => {
  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), 'slicer-toolpath-limit-'));
  t.after(() => fs.rm(workDir, { recursive: true, force: true }));
  const gcodePath = path.join(workDir, 'output.gcode');
  await fs.writeFile(gcodePath, gcode, { mode: 0o600 });
  await assert.rejects(compileProductionToolpath({
    gcodePath,
    workDir,
    run,
    effectiveConfiguration,
    gcodeArtifact: { checksumSha256: sha256(gcode) },
    sliceEvidenceChecksumSha256: 'd'.repeat(64),
    summary: { layerCount: 2 },
    maximumBytes: 128
  }), { code: 'slicer_toolpath_size_invalid' });
});
